### ISSUE TITLE
Lines in sidebar

### ISSUE THREAD

**Issue by ourhalcyondays** [owenvachell/Obsidian-Graphite-Coast#2]
Thank you for this wonderful theme, it's the best one I've come across for obsidian! A perfect balance of minimal and colour accents. 

I don't know if this is an issue, but these lines show up in the sidebar, and they don't seem uniform in width. I'd really love to know how I can get rid of these.

![image](https://user-images.githubusercontent.com/70455008/121197572-69e45a80-c83f-11eb-8157-2a9035cb6791.png)

Thanks for your help!

**Comment by owenvachell** [comment]
That's an impressive eagle eye, well spotted and thank you. I've fixed it now. Please overwrite your theme css file with the one in this repo and it will disappear. If you could let me know when you've checked it so I can close this issue, I'd appreciate it.

Edit: This fix has removed the relationship lines between folders. Will work on a fix for that and let you know when it's done.

**Comment by ourhalcyondays** [comment]
Thank you for the quick fix, it worked perfectly! As you said, the folder relationship lines are indeed gone, but I'm very glad to hear you're on it. :)

Thanks again!

**Comment by owenvachell** [comment]
this should be fixed now. There's also improvements to that highlight the relationship line on hover. Also, there's relationship lines for the outline and tag views. Let me know what you think and I'll close this if you're happy.

**Comment by ourhalcyondays** [comment]
Looks fantastic!! Great job and thank you. :)
